import { Dimension, QuestionType, ConditionOperator, type Question } from '../types/index.js';

export const questions: Question[] = [
  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 1: STRATEGIC INTENT (includes user profile/role)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'STRAT_000',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What best describes your role?',
    helpText: 'This helps us tailor the Claude Code setup to your needs and skill level.',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'developer', label: 'Software Developer / Engineer', description: 'Writes and maintains code' },
      { key: 'devops', label: 'DevOps / Platform / SRE', description: 'Infrastructure, CI/CD, deployment' },
      { key: 'lead', label: 'Tech Lead / Architect', description: 'Technical leadership and design' },
      { key: 'ba', label: 'Business Analyst', description: 'Requirements, specifications, process analysis' },
      { key: 'pm', label: 'Product Manager / Product Owner', description: 'Product strategy and prioritization' },
      { key: 'executive', label: 'Executive / Director', description: 'Strategic oversight, decisions, reporting' },
      { key: 'qa', label: 'QA / Test Engineer', description: 'Quality assurance and test automation' },
      { key: 'data', label: 'Data Analyst / Data Scientist', description: 'Data analysis, ML, reporting' },
    ],
    required: true,
    order: 0,
    showConditions: [],
    tags: ['role', 'user_profile'],
  },
  {
    id: 'STRAT_000a',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'How would you rate your technical proficiency?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'beginner', label: 'Beginner', description: 'New to coding or command-line tools' },
      { key: 'intermediate', label: 'Intermediate', description: 'Comfortable with code and basic DevOps' },
      { key: 'advanced', label: 'Advanced', description: 'Deep technical expertise' },
      { key: 'non_technical', label: 'Non-technical', description: 'I primarily work with documents, reports, and strategy' },
    ],
    required: true,
    order: 0.5,
    showConditions: [],
    tags: ['proficiency', 'user_profile'],
  },
  {
    id: 'STRAT_001',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What is the primary purpose of your project?',
    helpText: 'Describe in a few words what your project or product does.',
    type: QuestionType.FREE_TEXT,
    required: true,
    order: 1,
    showConditions: [],
    tags: ['purpose', 'vision'],
  },
  {
    id: 'STRAT_002',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What industry does your project serve?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'healthcare', label: 'Healthcare / Life Sciences' },
      { key: 'finance', label: 'Financial Services / Fintech' },
      { key: 'ecommerce', label: 'E-Commerce / Retail' },
      { key: 'saas', label: 'SaaS / Enterprise Software' },
      { key: 'education', label: 'Education / EdTech' },
      { key: 'government', label: 'Government / Public Sector' },
      { key: 'manufacturing', label: 'Manufacturing / IoT' },
      { key: 'media', label: 'Media / Entertainment / Gaming' },
      { key: 'other', label: 'Other' },
    ],
    required: true,
    order: 2,
    showConditions: [],
    tags: ['industry', 'domain'],
  },
  {
    id: 'STRAT_003',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'If "Other", what industry?',
    type: QuestionType.FREE_TEXT,
    required: true,
    order: 3,
    showConditions: [
      { questionId: 'STRAT_002', operator: ConditionOperator.EQUALS, value: 'other' },
    ],
    tags: ['industry', 'domain'],
  },
  {
    id: 'STRAT_004',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What are your primary outcome expectations?',
    helpText: 'Select all that apply to what you want Claude Code to help you achieve.',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'velocity', label: 'Increase development velocity', description: 'Ship features faster' },
      { key: 'quality', label: 'Improve code quality', description: 'Fewer bugs, better patterns' },
      { key: 'compliance', label: 'Ensure compliance', description: 'Regulatory / security adherence' },
      { key: 'onboarding', label: 'Accelerate onboarding', description: 'Help new devs ramp up faster' },
      { key: 'automation', label: 'Automate DevOps workflows', description: 'CI/CD, testing, deployment' },
      { key: 'cost', label: 'Optimize AI costs', description: 'Control Claude API spending' },
    ],
    required: true,
    order: 4,
    showConditions: [],
    tags: ['goals', 'outcomes'],
  },
  {
    id: 'STRAT_005',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What stage is your project in?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'greenfield', label: 'Greenfield / New project', description: 'Starting from scratch' },
      { key: 'active', label: 'Active development', description: 'Ongoing feature work' },
      { key: 'maintenance', label: 'Maintenance mode', description: 'Mostly bug fixes and updates' },
      { key: 'migration', label: 'Major migration / refactor', description: 'Large-scale restructuring' },
    ],
    required: true,
    order: 5,
    showConditions: [],
    tags: ['maturity', 'lifecycle'],
  },
  {
    id: 'STRAT_006',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'How critical is this project to your organization?',
    type: QuestionType.SCALE,
    helpText: '1 = Internal tool / side project, 5 = Revenue-critical production system',
    required: true,
    order: 6,
    showConditions: [],
    tags: ['criticality', 'risk'],
  },
  {
    id: 'STRAT_007',
    dimension: Dimension.STRATEGIC_INTENT,
    text: 'What is the expected lifespan of this project?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'short', label: 'Short-term (< 6 months)' },
      { key: 'medium', label: 'Medium-term (6-24 months)' },
      { key: 'long', label: 'Long-term (2+ years)' },
      { key: 'indefinite', label: 'Indefinite / Ongoing product' },
    ],
    required: false,
    order: 7,
    showConditions: [],
    tags: ['longevity', 'future'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 2: PROBLEM DEFINITION
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'PROB_001',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'What are the biggest pain points in your current development workflow?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'slow_reviews', label: 'Slow code reviews' },
      { key: 'inconsistent_code', label: 'Inconsistent code patterns' },
      { key: 'test_gaps', label: 'Insufficient test coverage' },
      { key: 'docs_outdated', label: 'Outdated documentation' },
      { key: 'deploy_manual', label: 'Manual deployment processes' },
      { key: 'onboarding_slow', label: 'Slow developer onboarding' },
      { key: 'security_gaps', label: 'Security vulnerabilities slipping through' },
      { key: 'context_switching', label: 'Too much context switching' },
    ],
    required: true,
    order: 1,
    showConditions: [],
    tags: ['pain_points', 'problems'],
  },
  {
    id: 'PROB_002',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'Describe the single most important problem you want to solve with Claude Code.',
    type: QuestionType.FREE_TEXT,
    required: true,
    order: 2,
    showConditions: [],
    tags: ['primary_problem'],
  },
  {
    id: 'PROB_003',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'Are there existing solutions or tools you have tried that fell short?',
    type: QuestionType.FREE_TEXT,
    required: false,
    order: 3,
    showConditions: [],
    tags: ['prior_solutions'],
  },
  {
    id: 'PROB_004',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'Who is the primary audience for the Claude Code setup?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'individual', label: 'Just me (individual developer)' },
      { key: 'team', label: 'My development team' },
      { key: 'org', label: 'Multiple teams / organization-wide' },
      { key: 'oss', label: 'Open source contributors' },
    ],
    required: true,
    order: 4,
    showConditions: [],
    tags: ['audience', 'scope'],
  },
  {
    id: 'PROB_005',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'How important is enforcing consistent practices across the team?',
    type: QuestionType.SCALE,
    helpText: '1 = Not important (flexible), 5 = Critical (strict enforcement)',
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'PROB_004', operator: ConditionOperator.ANY_OF, value: ['team', 'org', 'oss'] },
    ],
    tags: ['consistency', 'enforcement'],
  },
  {
    id: 'PROB_006',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'Are there specific quality gates that must pass before code can be merged?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'tests_pass', label: 'All tests must pass' },
      { key: 'coverage_min', label: 'Minimum test coverage threshold' },
      { key: 'lint_clean', label: 'Linting must be clean' },
      { key: 'type_check', label: 'Type checking must pass' },
      { key: 'security_scan', label: 'Security scan required' },
      { key: 'peer_review', label: 'Peer review required' },
      { key: 'docs_updated', label: 'Documentation must be updated' },
      { key: 'none', label: 'No formal quality gates yet' },
    ],
    required: true,
    order: 6,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['quality_gates', 'enforcement'],
  },
  {
    id: 'PROB_007',
    dimension: Dimension.PROBLEM_DEFINITION,
    text: 'Do you want Claude Code to enforce TDD (Test-Driven Development)?',
    type: QuestionType.YES_NO,
    helpText: 'If yes, hooks will block implementation until tests exist.',
    required: true,
    order: 7,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['tdd', 'testing', 'enforcement'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 3: OPERATIONAL REALITY
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'OPS_001',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'What is the size of your development team?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'solo', label: 'Solo developer (just me)' },
      { key: 'small', label: 'Small team (2-5 developers)' },
      { key: 'medium', label: 'Medium team (6-15 developers)' },
      { key: 'large', label: 'Large team (15+ developers)' },
    ],
    required: true,
    order: 1,
    showConditions: [],
    tags: ['team_size', 'collaboration'],
  },
  {
    id: 'OPS_002',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'What branching strategy does your team use?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'gitflow', label: 'Git Flow (develop/release/feature branches)' },
      { key: 'trunk', label: 'Trunk-based development' },
      { key: 'github_flow', label: 'GitHub Flow (feature branches + main)' },
      { key: 'none', label: 'No formal strategy' },
    ],
    required: true,
    order: 2,
    showConditions: [
      { questionId: 'OPS_001', operator: ConditionOperator.NOT_EQUALS, value: 'solo' },
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['branching', 'git', 'workflow'],
  },
  {
    id: 'OPS_003',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'Do team members work on features in parallel that often touch the same files?',
    type: QuestionType.YES_NO,
    helpText: 'This helps determine if worktree isolation is needed.',
    required: true,
    order: 3,
    showConditions: [
      { questionId: 'OPS_001', operator: ConditionOperator.NOT_EQUALS, value: 'solo' },
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['parallel_work', 'worktrees', 'conflicts'],
  },
  {
    id: 'OPS_004',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'How do you currently handle code reviews?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'pr_reviews', label: 'Pull request reviews on GitHub/GitLab' },
      { key: 'pair', label: 'Pair programming' },
      { key: 'async', label: 'Async review via comments' },
      { key: 'none', label: 'No formal review process' },
    ],
    required: true,
    order: 4,
    showConditions: [
      { questionId: 'OPS_001', operator: ConditionOperator.NOT_EQUALS, value: 'solo' },
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['code_review', 'collaboration'],
  },
  {
    id: 'OPS_005',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'Do you want to use Claude Code agent teams for parallel coordination?',
    helpText: 'Agent teams allow 3-5 Claude instances to coordinate via shared task lists.',
    type: QuestionType.YES_NO,
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'OPS_001', operator: ConditionOperator.ANY_OF, value: ['medium', 'large'] },
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['agent_teams', 'parallel', 'advanced'],
  },
  {
    id: 'OPS_006',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'How many Claude Code sessions do you typically run simultaneously?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: '1', label: 'One at a time' },
      { key: '2-3', label: '2-3 parallel sessions' },
      { key: '4+', label: '4+ parallel sessions' },
    ],
    required: true,
    order: 6,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['parallelism', 'worktrees'],
  },
  {
    id: 'OPS_007',
    dimension: Dimension.OPERATIONAL_REALITY,
    text: 'What is your typical development workflow?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'feature_branch', label: 'Feature branch → PR → merge' },
      { key: 'direct_commit', label: 'Direct commits to main' },
      { key: 'worktree', label: 'Worktree-based parallel development' },
      { key: 'mixed', label: 'Mixed / varies by task' },
    ],
    required: true,
    order: 7,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['workflow', 'development_process'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 4: TECHNOLOGY REQUIREMENTS
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'TECH_001',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What programming languages does your project use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'typescript', label: 'TypeScript / JavaScript' },
      { key: 'python', label: 'Python' },
      { key: 'java', label: 'Java / Kotlin' },
      { key: 'go', label: 'Go' },
      { key: 'rust', label: 'Rust' },
      { key: 'csharp', label: 'C# / .NET' },
      { key: 'swift', label: 'Swift' },
      { key: 'ruby', label: 'Ruby' },
    ],
    required: true,
    order: 1,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['languages', 'stack'],
  },
  {
    id: 'TECH_002',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'Any additional languages not listed above?',
    type: QuestionType.FREE_TEXT,
    required: false,
    order: 2,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['languages', 'stack'],
  },
  {
    id: 'TECH_003',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What frameworks or major libraries are core to your project?',
    helpText: 'E.g., React, Spring Boot, Django, Express, Rails, Next.js, FastAPI',
    type: QuestionType.FREE_TEXT,
    required: true,
    order: 3,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['frameworks', 'stack'],
  },
  {
    id: 'TECH_004',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What IDEs or editors does your team use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'vscode', label: 'VS Code' },
      { key: 'jetbrains', label: 'JetBrains (IntelliJ, WebStorm, PyCharm, etc.)' },
      { key: 'neovim', label: 'Neovim / Vim' },
      { key: 'terminal', label: 'Terminal-only (no IDE)' },
      { key: 'other', label: 'Other' },
    ],
    required: true,
    order: 4,
    showConditions: [],
    tags: ['ide', 'editor', 'devtools'],
  },
  {
    id: 'TECH_005',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What build tools do you use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'npm', label: 'npm / yarn / pnpm' },
      { key: 'maven', label: 'Maven' },
      { key: 'gradle', label: 'Gradle' },
      { key: 'pip', label: 'pip / poetry / uv' },
      { key: 'cargo', label: 'Cargo (Rust)' },
      { key: 'go_mod', label: 'Go modules' },
      { key: 'make', label: 'Make / CMake' },
      { key: 'docker', label: 'Docker / docker-compose' },
    ],
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['build', 'tooling'],
  },
  {
    id: 'TECH_006',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What testing frameworks do you use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'jest', label: 'Jest / Vitest' },
      { key: 'pytest', label: 'pytest' },
      { key: 'junit', label: 'JUnit' },
      { key: 'go_test', label: 'Go testing' },
      { key: 'rspec', label: 'RSpec' },
      { key: 'playwright', label: 'Playwright / Cypress (E2E)' },
      { key: 'none', label: 'No testing framework yet' },
    ],
    required: true,
    order: 6,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['testing', 'quality'],
  },
  {
    id: 'TECH_007',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What CI/CD platform do you use?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'github_actions', label: 'GitHub Actions' },
      { key: 'gitlab_ci', label: 'GitLab CI' },
      { key: 'jenkins', label: 'Jenkins' },
      { key: 'circleci', label: 'CircleCI' },
      { key: 'azure_devops', label: 'Azure DevOps' },
      { key: 'none', label: 'No CI/CD yet' },
      { key: 'other', label: 'Other' },
    ],
    required: true,
    order: 7,
    showConditions: [],
    tags: ['cicd', 'automation', 'devops'],
  },
  {
    id: 'TECH_008',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What containerization / orchestration do you use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'docker', label: 'Docker' },
      { key: 'kubernetes', label: 'Kubernetes' },
      { key: 'compose', label: 'Docker Compose' },
      { key: 'serverless', label: 'Serverless (Lambda, Cloud Functions)' },
      { key: 'none', label: 'None / bare metal' },
    ],
    required: true,
    order: 8,
    showConditions: [],
    tags: ['containers', 'deployment', 'infrastructure'],
  },
  {
    id: 'TECH_009',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What monitoring / observability tools do you use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'datadog', label: 'Datadog' },
      { key: 'grafana', label: 'Grafana / Prometheus' },
      { key: 'sentry', label: 'Sentry (error tracking)' },
      { key: 'cloudwatch', label: 'AWS CloudWatch' },
      { key: 'newrelic', label: 'New Relic' },
      { key: 'elk', label: 'ELK Stack (Elasticsearch, Logstash, Kibana)' },
      { key: 'none', label: 'No monitoring yet' },
    ],
    required: false,
    order: 9,
    showConditions: [],
    tags: ['monitoring', 'observability', 'devops'],
  },
  {
    id: 'TECH_010',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What databases or data stores does your project use?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'postgres', label: 'PostgreSQL' },
      { key: 'mysql', label: 'MySQL' },
      { key: 'mongodb', label: 'MongoDB' },
      { key: 'redis', label: 'Redis' },
      { key: 'dynamodb', label: 'DynamoDB' },
      { key: 'sqlite', label: 'SQLite' },
      { key: 'elasticsearch', label: 'Elasticsearch' },
      { key: 'none', label: 'None / file-based' },
    ],
    required: false,
    order: 10,
    showConditions: [],
    tags: ['database', 'data', 'storage'],
  },
  {
    id: 'TECH_011',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What code formatting / linting tools do you currently use?',
    helpText: 'This determines which PostToolUse hooks to generate.',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'prettier', label: 'Prettier' },
      { key: 'eslint', label: 'ESLint' },
      { key: 'ruff', label: 'Ruff (Python)' },
      { key: 'black', label: 'Black (Python)' },
      { key: 'gofmt', label: 'gofmt / golangci-lint' },
      { key: 'rubocop', label: 'RuboCop' },
      { key: 'clippy', label: 'Clippy (Rust)' },
      { key: 'none', label: 'None yet' },
    ],
    required: true,
    order: 11,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['linting', 'formatting', 'quality'],
  },
  {
    id: 'TECH_012',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'Do you use a monorepo structure?',
    type: QuestionType.YES_NO,
    helpText: 'Monorepos benefit from sub-context CLAUDE.md files in each package.',
    required: true,
    order: 12,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['monorepo', 'project_structure'],
  },
  {
    id: 'TECH_013',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'Do you want to use local AI models to reduce API costs?',
    helpText: 'Local models via Ollama can handle linting, formatting, and lookups cheaply.',
    type: QuestionType.YES_NO,
    required: true,
    order: 13,
    showConditions: [
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['local_models', 'cost', 'ollama'],
  },
  {
    id: 'TECH_014',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'What hardware do you have available for local models?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: '16gb', label: '16GB RAM or less' },
      { key: '32gb', label: '32GB RAM' },
      { key: '64gb', label: '64GB RAM' },
      { key: '128gb+', label: '128GB+ RAM (e.g., M4 Max)' },
      { key: 'gpu', label: 'Dedicated GPU (NVIDIA RTX)' },
    ],
    required: true,
    order: 14,
    showConditions: [
      { questionId: 'TECH_013', operator: ConditionOperator.EQUALS, value: true },
      { questionId: 'STRAT_000', operator: ConditionOperator.NONE_OF, value: ['ba', 'pm', 'executive'] },
    ],
    tags: ['hardware', 'local_models', 'cost'],
  },
  {
    id: 'TECH_015',
    dimension: Dimension.TECHNOLOGY_REQUIREMENTS,
    text: 'Which MCP servers would be useful for your workflow?',
    helpText: 'MCP servers extend Claude Code with external capabilities.',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'github', label: 'GitHub MCP (PR/issue management)' },
      { key: 'context7', label: 'Context7 (library documentation)' },
      { key: 'sequential', label: 'Sequential Thinking (step-by-step reasoning)' },
      { key: 'filesystem', label: 'Filesystem (multi-file editing)' },
      { key: 'playwright', label: 'Playwright (browser testing)' },
      { key: 'database', label: 'Database MCP (query databases)' },
      { key: 'unsure', label: 'Not sure / recommend for me' },
    ],
    required: true,
    order: 15,
    showConditions: [],
    tags: ['mcp', 'tools', 'integrations'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 5: REGULATORY COMPLIANCE
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'REG_001',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Does your project handle sensitive or regulated data?',
    type: QuestionType.YES_NO,
    required: true,
    order: 1,
    showConditions: [],
    tags: ['security', 'compliance', 'sensitive_data'],
  },
  {
    id: 'REG_002',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Which compliance frameworks apply to your project?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'hipaa', label: 'HIPAA (healthcare data)' },
      { key: 'soc2', label: 'SOC 2' },
      { key: 'pci', label: 'PCI-DSS (payment data)' },
      { key: 'gdpr', label: 'GDPR (EU data protection)' },
      { key: 'fda', label: 'FDA (medical devices / life sciences)' },
      { key: 'fedramp', label: 'FedRAMP (US government)' },
      { key: 'none', label: 'None / Not applicable' },
    ],
    required: true,
    order: 2,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['compliance_frameworks', 'regulation'],
  },
  {
    id: 'REG_003',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Does your code handle PHI (Protected Health Information)?',
    helpText: 'PHI includes patient names, medical records, SSNs, etc.',
    type: QuestionType.YES_NO,
    required: true,
    order: 3,
    showConditions: [
      { questionId: 'REG_002', operator: ConditionOperator.CONTAINS, value: 'hipaa' },
    ],
    tags: ['phi', 'hipaa', 'health_data'],
  },
  {
    id: 'REG_004',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Does your code handle PII (Personally Identifiable Information)?',
    helpText: 'PII includes names, emails, addresses, SSNs, credit card numbers.',
    type: QuestionType.YES_NO,
    required: true,
    order: 4,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['pii', 'personal_data', 'security'],
  },
  {
    id: 'REG_005',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need audit logging for all code changes?',
    type: QuestionType.YES_NO,
    helpText: 'Audit logs track who changed what, when, for compliance reporting.',
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['audit', 'logging', 'compliance'],
  },
  {
    id: 'REG_006',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Are there directories or file paths that must never be accessed by Claude Code?',
    helpText: 'E.g., patient_data/, phi/, credentials/, secrets/',
    type: QuestionType.FREE_TEXT,
    required: false,
    order: 6,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['restricted_paths', 'security', 'deny_rules'],
  },
  {
    id: 'REG_007',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need secret scanning (API keys, tokens, passwords in code)?',
    type: QuestionType.YES_NO,
    required: true,
    order: 7,
    showConditions: [],
    tags: ['secrets', 'scanning', 'security'],
  },
  {
    id: 'REG_008',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'How strict should permission controls be?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'permissive', label: 'Permissive (allow most, ask rarely)', description: 'Fastest workflow, lower guardrails' },
      { key: 'balanced', label: 'Balanced (allow safe ops, ask for risky ones)', description: 'Good default for most teams' },
      { key: 'strict', label: 'Strict (deny dangerous, ask for most)', description: 'High security, slower workflow' },
      { key: 'lockdown', label: 'Lockdown (deny most, allow only safe reads)', description: 'Maximum security, compliance-heavy' },
    ],
    required: true,
    order: 8,
    showConditions: [],
    tags: ['permissions', 'security_level'],
  },
  {
    id: 'REG_009',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do safety-critical files require approval before modification?',
    helpText: 'E.g., auth modules, encryption, crisis detection, billing logic.',
    type: QuestionType.YES_NO,
    required: true,
    order: 9,
    showConditions: [],
    tags: ['protected_files', 'approval_workflow', 'safety'],
  },
  {
    id: 'REG_010',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'List the file patterns that require protection (if any).',
    helpText: 'E.g., src/auth/**, src/billing/**, src/crypto/**',
    type: QuestionType.FREE_TEXT,
    required: false,
    order: 10,
    showConditions: [
      { questionId: 'REG_009', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['protected_files', 'approval_workflow'],
  },

  // --- CISO-Level Data Privacy & Audit Controls ---

  {
    id: 'REG_011',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Does your organization require data classification labeling?',
    helpText: 'E.g., PUBLIC, INTERNAL, CONFIDENTIAL, RESTRICTED labels on data assets.',
    type: QuestionType.YES_NO,
    required: true,
    order: 11,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['data_classification', 'ciso', 'governance'],
  },
  {
    id: 'REG_012',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need Data Loss Prevention (DLP) controls in Claude Code?',
    helpText: 'DLP hooks scan outbound content for sensitive patterns (SSNs, credit cards, API keys, medical record numbers) and block before they reach the API.',
    type: QuestionType.YES_NO,
    required: true,
    order: 12,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['dlp', 'data_loss_prevention', 'ciso', 'security'],
  },
  {
    id: 'REG_012a',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Which sensitive data patterns should DLP hooks detect?',
    type: QuestionType.MULTI_CHOICE,
    options: [
      { key: 'ssn', label: 'Social Security Numbers (SSN)' },
      { key: 'credit_card', label: 'Credit card numbers' },
      { key: 'api_keys', label: 'API keys and tokens' },
      { key: 'mrn', label: 'Medical Record Numbers (MRN)' },
      { key: 'email_phone', label: 'Email addresses and phone numbers' },
      { key: 'aws_keys', label: 'AWS access keys' },
      { key: 'private_keys', label: 'Private keys and certificates' },
      { key: 'custom', label: 'Custom patterns (will specify)' },
    ],
    required: true,
    order: 13,
    showConditions: [
      { questionId: 'REG_012', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['dlp', 'patterns', 'sensitive_data'],
  },
  {
    id: 'REG_012b',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Specify custom DLP regex patterns (one per line).',
    helpText: 'E.g., MRN-\\d{8}, ACCT-\\d{10}',
    type: QuestionType.FREE_TEXT,
    required: false,
    order: 14,
    showConditions: [
      { questionId: 'REG_012a', operator: ConditionOperator.CONTAINS, value: 'custom' },
    ],
    tags: ['dlp', 'custom_patterns'],
  },
  {
    id: 'REG_013',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need context sanitization before data reaches the Claude API?',
    helpText: 'Ensures sensitive data in .claudeignore and deny rules never enters the LLM context. Critical for HIPAA/SOC2 compliance.',
    type: QuestionType.YES_NO,
    required: true,
    order: 15,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['context_sanitization', 'data_privacy', 'ciso'],
  },
  {
    id: 'REG_014',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need a full session audit trail?',
    helpText: 'Logs every tool call, file access, and code change with timestamps and user identity. Required for many compliance frameworks.',
    type: QuestionType.YES_NO,
    required: true,
    order: 16,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['session_audit_trail', 'audit', 'ciso', 'compliance'],
  },
  {
    id: 'REG_014a',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Where should audit logs be stored?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'local_file', label: 'Local file (.claude/logs/)', description: 'Simple, no external deps' },
      { key: 'siem', label: 'SIEM integration (Splunk, Datadog, etc.)', description: 'Enterprise security monitoring' },
      { key: 'cloud', label: 'Cloud storage (S3, CloudWatch)', description: 'Durable, centralized' },
      { key: 'both', label: 'Local + external (belt-and-suspenders)', description: 'Maximum coverage' },
    ],
    required: true,
    order: 17,
    showConditions: [
      { questionId: 'REG_014', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['audit_storage', 'siem', 'logging'],
  },
  {
    id: 'REG_015',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need output review controls?',
    helpText: 'Scans Claude-generated code for sensitive data patterns before writing to files. Prevents accidental exposure of hardcoded credentials or test data containing real values.',
    type: QuestionType.YES_NO,
    required: true,
    order: 18,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['output_review', 'code_scanning', 'ciso'],
  },
  {
    id: 'REG_016',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need to block Claude Code from accessing specific environment variables?',
    helpText: 'Prevents leaking database passwords, API tokens, or service credentials through env var access.',
    type: QuestionType.YES_NO,
    required: true,
    order: 19,
    showConditions: [
      { questionId: 'REG_008', operator: ConditionOperator.ANY_OF, value: ['strict', 'lockdown'] },
    ],
    tags: ['env_protection', 'credentials', 'security'],
  },
  {
    id: 'REG_017',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Does your organization require Zero Data Retention (ZDR) for AI API usage?',
    helpText: 'Anthropic offers ZDR for enterprise plans. Ensures no prompts or completions are stored by Anthropic.',
    type: QuestionType.YES_NO,
    required: true,
    order: 20,
    showConditions: [
      { questionId: 'REG_001', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['zdr', 'data_retention', 'enterprise', 'ciso'],
  },
  {
    id: 'REG_018',
    dimension: Dimension.REGULATORY_COMPLIANCE,
    text: 'Do you need network egress controls for Claude Code?',
    helpText: 'Restricts which external URLs/APIs Claude can access via Bash/curl. Prevents data exfiltration.',
    type: QuestionType.YES_NO,
    required: true,
    order: 21,
    showConditions: [
      { questionId: 'REG_008', operator: ConditionOperator.ANY_OF, value: ['strict', 'lockdown'] },
    ],
    tags: ['network_egress', 'exfiltration', 'ciso', 'security'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 6: FINANCIAL CONSTRAINTS
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'FIN_001',
    dimension: Dimension.FINANCIAL_CONSTRAINTS,
    text: 'What is your Claude API budget sensitivity?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'minimal', label: 'Very cost-sensitive (< $5/day target)' },
      { key: 'moderate', label: 'Moderate ($5-20/day is fine)' },
      { key: 'enterprise', label: 'Enterprise (cost is not a primary concern)' },
    ],
    required: true,
    order: 1,
    showConditions: [],
    tags: ['budget', 'cost'],
  },
  {
    id: 'FIN_002',
    dimension: Dimension.FINANCIAL_CONSTRAINTS,
    text: 'Do you want to use model routing to optimize costs?',
    helpText: 'Routes simple tasks to cheaper models (Haiku) and complex tasks to Opus.',
    type: QuestionType.YES_NO,
    required: true,
    order: 2,
    showConditions: [],
    tags: ['model_routing', 'cost_optimization'],
  },
  {
    id: 'FIN_003',
    dimension: Dimension.FINANCIAL_CONSTRAINTS,
    text: 'Which model routing strategy do you prefer?',
    type: QuestionType.SINGLE_CHOICE,
    options: [
      { key: 'opusplan', label: 'OpusPlan (Opus for planning, Sonnet for execution)', description: '~68% cost savings' },
      { key: 'sonnetplan', label: 'SonnetPlan (Sonnet for planning, Haiku for execution)', description: 'Maximum savings, lower quality' },
      { key: 'manual', label: 'Manual (/quick, /code, /think commands)', description: 'Full control' },
      { key: 'auto', label: 'Automated (claude-router plugin)', description: 'AI-based routing' },
    ],
    required: true,
    order: 3,
    showConditions: [
      { questionId: 'FIN_002', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['model_routing', 'cost_optimization'],
  },
  {
    id: 'FIN_004',
    dimension: Dimension.FINANCIAL_CONSTRAINTS,
    text: 'Do you want subagents to use a cheaper model by default?',
    helpText: 'Setting CLAUDE_CODE_SUBAGENT_MODEL=haiku saves ~80% on subagent operations.',
    type: QuestionType.YES_NO,
    required: true,
    order: 4,
    showConditions: [
      { questionId: 'FIN_002', operator: ConditionOperator.EQUALS, value: true },
    ],
    tags: ['subagents', 'cost_optimization'],
  },
  {
    id: 'FIN_005',
    dimension: Dimension.FINANCIAL_CONSTRAINTS,
    text: 'Do you want to limit thinking tokens to reduce costs?',
    helpText: 'Reducing MAX_THINKING_TOKENS to 10,000 cuts hidden costs by ~70%.',
    type: QuestionType.YES_NO,
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'FIN_001', operator: ConditionOperator.ANY_OF, value: ['minimal', 'moderate'] },
    ],
    tags: ['thinking_tokens', 'cost_optimization'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DIMENSION 7: INNOVATION & FUTURE-PROOFING
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'INNOV_001',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want to use the plugin system for reusable configurations?',
    helpText: 'Plugins package rules, commands, agents, skills, and hooks into installable bundles.',
    type: QuestionType.YES_NO,
    required: true,
    order: 1,
    showConditions: [],
    tags: ['plugins', 'extensibility'],
  },
  {
    id: 'INNOV_002',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want to set up document state tracking?',
    helpText: 'Categorizes docs as CURRENT, FUTURE, REFERENCE, or ARCHIVED for lifecycle management.',
    type: QuestionType.YES_NO,
    required: true,
    order: 2,
    showConditions: [],
    tags: ['documentation', 'lifecycle'],
  },
  {
    id: 'INNOV_003',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want an association map linking code, tests, docs, and infrastructure?',
    helpText: 'Enables impact analysis and co-commit enforcement across related files.',
    type: QuestionType.YES_NO,
    required: true,
    order: 3,
    showConditions: [],
    tags: ['association_map', 'impact_analysis'],
  },
  {
    id: 'INNOV_004',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want to set up memory management for cross-session context?',
    helpText: 'Elastic memory files persist domain knowledge, architecture insights, and data schemas.',
    type: QuestionType.YES_NO,
    required: true,
    order: 4,
    showConditions: [],
    tags: ['memory', 'context_persistence'],
  },
  {
    id: 'INNOV_005',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want Claude Code integration with your CI/CD pipeline?',
    helpText: 'Headless mode enables automated code review, triage, and PR comments in CI.',
    type: QuestionType.YES_NO,
    required: true,
    order: 5,
    showConditions: [
      { questionId: 'TECH_007', operator: ConditionOperator.NOT_EQUALS, value: 'none' },
    ],
    tags: ['cicd_integration', 'automation'],
  },
  {
    id: 'INNOV_006',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want to generate custom slash commands for your team workflows?',
    helpText: 'E.g., /review, /deploy-check, /test-coverage, /sync-memory',
    type: QuestionType.YES_NO,
    required: true,
    order: 6,
    showConditions: [],
    tags: ['commands', 'team_workflows'],
  },
  {
    id: 'INNOV_007',
    dimension: Dimension.INNOVATION_FUTURE,
    text: 'Do you want to generate specialized agents for autonomous tasks?',
    helpText: 'E.g., security-reviewer, compliance-checker, test-writer agents with restricted tool access.',
    type: QuestionType.YES_NO,
    required: true,
    order: 7,
    showConditions: [],
    tags: ['agents', 'automation', 'specialization'],
  },
];
