import type { GeneratedFile, UserProfile, ValidationResult } from '../../types/index.js';
import { getGeneratorForFile } from '../../evaluation/archetype-registry.js';

export interface BuildPrTemplateInput {
  profile: UserProfile;
  files: readonly GeneratedFile[];
  validation?: ValidationResult;
  /** When launched from autopilot (6E), attach the drift summary that triggered the PR. */
  driftSummary?: {
    totalDrift: number;
    missing: number;
    modifiedByUser: number;
    modifiedStaleStamp: number;
    versionMismatch: number;
    extra: number;
  };
  /**
   * Contributors map from session data (6C). Shown as an attribution table
   * when supplied so compliance reviewers can see who answered what.
   */
  contributors?: Record<string, number>;
  /** Optional override for the title (default: "EmbedIQ: regenerate configuration"). */
  titleOverride?: string;
  /** Optional commit message (default: derived from title). */
  commitMessageOverride?: string;
}

export interface BuiltPrTemplate {
  title: string;
  body: string;
  commitMessage: string;
}

/**
 * Build the PR body from the current generation. Sections — in order:
 *
 *   Summary    — one-paragraph human summary (profile + file count)
 *   Changes    — per-generator file list grouped by target family
 *   Validation — pass/fail counts with the first few failures
 *   Contributors — attribution table (only when session data is supplied)
 *   Drift      — summary of the drift that triggered this PR (autopilot)
 *
 * The template is deliberately simple for v1. Making it a composable
 * skill (so teams customize the format) is the next iteration — see
 * the 6F integration note in the ROADMAP.
 */
export function buildPrTemplate(input: BuildPrTemplateInput): BuiltPrTemplate {
  const { profile, files, validation } = input;
  const title = input.titleOverride ?? 'EmbedIQ: regenerate configuration';
  const commitMessage = input.commitMessageOverride
    ?? `${title}\n\n${shortSummary(profile, files.length)}\n\nGenerated by EmbedIQ.`;

  const lines: string[] = [];
  lines.push('## Summary');
  lines.push('');
  lines.push(shortSummary(profile, files.length));
  if (profile.complianceFrameworks.length > 0) {
    lines.push('');
    lines.push(
      `**Compliance frameworks:** ${profile.complianceFrameworks
        .map((f) => f.toUpperCase())
        .join(', ')}`,
    );
  }
  lines.push('');

  // ─── Changes ───
  lines.push('## Changes');
  lines.push('');
  const grouped = groupByGenerator(files);
  const generators = Array.from(grouped.keys()).sort();
  if (generators.length === 0) {
    lines.push('_No files generated._');
  } else {
    for (const gen of generators) {
      const group = grouped.get(gen)!;
      lines.push(`- **${gen}** (${group.length} file${group.length === 1 ? '' : 's'})`);
      for (const f of group) lines.push(`  - \`${f.relativePath}\``);
    }
  }
  lines.push('');

  // ─── Validation ───
  if (validation) {
    const passed = validation.checks.filter((c) => c.passed).length;
    const failed = validation.checks.filter((c) => !c.passed && c.severity === 'error').length;
    const warned = validation.checks.filter((c) => !c.passed && c.severity === 'warning').length;
    lines.push('## Validation');
    lines.push('');
    lines.push(
      `**Status:** ${validation.passed ? '✅ passed' : '❌ failed'} — ${passed} pass / ${failed} fail / ${warned} warn`,
    );
    if (validation.summary) lines.push('', validation.summary);

    const failures = validation.checks.filter((c) => !c.passed).slice(0, 5);
    if (failures.length > 0) {
      lines.push('', '<details><summary>Failures</summary>', '');
      for (const f of failures) {
        lines.push(`- **${f.severity.toUpperCase()}**: ${f.name} — ${f.message}`);
      }
      lines.push('', '</details>');
    }
    lines.push('');
  }

  // ─── Contributors ───
  const contributorEntries = Object.entries(input.contributors ?? {})
    .filter(([, count]) => count > 0)
    .sort((a, b) => b[1] - a[1]);
  if (contributorEntries.length > 0) {
    lines.push('## Contributors');
    lines.push('');
    lines.push('| Contributor | Answers |');
    lines.push('|---|---|');
    for (const [userId, count] of contributorEntries) {
      lines.push(`| \`${escapePipe(userId)}\` | ${count} |`);
    }
    lines.push('');
  }

  // ─── Drift summary ───
  if (input.driftSummary) {
    const d = input.driftSummary;
    lines.push('## Drift that triggered this PR');
    lines.push('');
    lines.push(
      `Total drift: **${d.totalDrift}** — ${d.missing} missing, ${d.modifiedByUser} modified-by-user, `
        + `${d.modifiedStaleStamp} modified-stale-stamp, ${d.versionMismatch} version-mismatch, ${d.extra} extra.`,
    );
    lines.push('');
  }

  lines.push('---');
  lines.push('_PR opened by EmbedIQ — review and approve to adopt the regenerated configuration._');

  return { title, body: lines.join('\n'), commitMessage };
}

// ─── helpers ──────────────────────────────────────────────────────────────

function shortSummary(profile: UserProfile, fileCount: number): string {
  const roleLabel = profile.role.charAt(0).toUpperCase() + profile.role.slice(1);
  const domainLabel = profile.businessDomain
    ? ` for **${profile.businessDomain}**`
    : '';
  const industryLabel = profile.industry ? ` (${profile.industry})` : '';
  return `${roleLabel} configuration${domainLabel}${industryLabel} — ${fileCount} file${fileCount === 1 ? '' : 's'}.`;
}

function groupByGenerator(files: readonly GeneratedFile[]): Map<string, GeneratedFile[]> {
  const out = new Map<string, GeneratedFile[]>();
  for (const f of files) {
    const gen = getGeneratorForFile(f.relativePath) ?? 'uncategorized';
    const arr = out.get(gen);
    if (arr) arr.push(f);
    else out.set(gen, [f]);
  }
  return out;
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, '\\|');
}
