import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, mkdir, writeFile, rm, cp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { detectDrift, DriftError } from '../../src/autopilot/drift-detector.js';
import { renderDriftJson, renderDriftText } from '../../src/autopilot/drift-reporter.js';

const FIXTURE_ROOT = resolve(__dirname, '../fixtures/golden-configs/minimal-developer');
const FIXTURE_ANSWERS = join(FIXTURE_ROOT, 'answers.yaml');
const FIXTURE_EXPECTED = join(FIXTURE_ROOT, 'expected');

describe('detectDrift — clean cases', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'embediq-drift-'));
    await cp(FIXTURE_EXPECTED, dir, { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('reports clean when the target matches the expected golden exactly', async () => {
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    expect(report.clean).toBe(true);
    expect(report.totals.missing).toBe(0);
    expect(report.totals.modifiedByUser).toBe(0);
    expect(report.totals.extra).toBe(0);
    expect(report.totals.match).toBeGreaterThan(0);
  });

  it('labels the answer source via answerSourceLabel when provided', async () => {
    const report = await detectDrift({
      targetDir: dir,
      answers: FIXTURE_ANSWERS,
      answerSourceLabel: 'archetype:minimal-developer',
    });
    expect(report.answerSource).toBe('archetype:minimal-developer');
  });
});

describe('detectDrift — drift scenarios', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'embediq-drift-'));
    await cp(FIXTURE_EXPECTED, dir, { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('detects a missing file', async () => {
    await rm(join(dir, '.claude/rules/testing.md'));
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    expect(report.clean).toBe(false);
    expect(report.totals.missing).toBe(1);
    const entry = report.entries.find((e) => e.relativePath === '.claude/rules/testing.md');
    expect(entry?.status).toBe('missing');
    expect(entry?.expectedContent).toBeDefined();
  });

  it('detects an extra file inside a managed subtree', async () => {
    const extraPath = join(dir, '.claude/rules/rogue.md');
    await mkdir(dirname(extraPath), { recursive: true });
    await writeFile(extraPath, '# rogue rule\n', 'utf-8');
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    expect(report.totals.extra).toBe(1);
    const entry = report.entries.find((e) => e.relativePath === '.claude/rules/rogue.md');
    expect(entry?.status).toBe('extra');
  });

  it('ignores files outside managed subtrees (e.g. user source code)', async () => {
    await writeFile(join(dir, 'src_user_file.ts'), 'export const x = 1;\n', 'utf-8');
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    expect(report.clean).toBe(true);
  });

  it('flags a modified file without a stamp as modified-by-user', async () => {
    const path = join(dir, 'CLAUDE.md');
    const original = await readFile(path, 'utf-8');
    await writeFile(path, original + '\n\n## User appended section\n', 'utf-8');

    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    expect(report.clean).toBe(false);
    const entry = report.entries.find((e) => e.relativePath === 'CLAUDE.md');
    expect(entry?.status).toBe('modified-by-user');
  });

  it('flags a modified file with a stamp as modified-stale-stamp', async () => {
    const path = join(dir, 'CLAUDE.md');
    const original = await readFile(path, 'utf-8');
    const stamped = `<!-- Generated by EmbedIQ v2.0.0 | schema:2 | 2026-01-01T00:00:00Z -->\n\n${original}\n\n## Edited after generation\n`;
    await writeFile(path, stamped, 'utf-8');

    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const entry = report.entries.find((e) => e.relativePath === 'CLAUDE.md');
    expect(entry?.status).toBe('modified-stale-stamp');
    expect(entry?.onDiskVersion).toBe('2.0.0');
  });

  it('flags a stamped file with an older version as version-mismatch', async () => {
    const path = join(dir, 'CLAUDE.md');
    const original = await readFile(path, 'utf-8');
    const stamped = `<!-- Generated by EmbedIQ v1.0.0 | schema:1 | 2025-01-01T00:00:00Z -->\n\n${original}\n\n## Old output\n`;
    await writeFile(path, stamped, 'utf-8');

    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const entry = report.entries.find((e) => e.relativePath === 'CLAUDE.md');
    expect(entry?.status).toBe('version-mismatch');
    expect(entry?.onDiskVersion).toBe('1.0.0');
  });

  it('treats stamp-only differences as match (whitespace-normalized)', async () => {
    const path = join(dir, 'CLAUDE.md');
    const original = await readFile(path, 'utf-8');
    const stampedSame = `<!-- Generated by EmbedIQ v2.0.0 | schema:2 | 2026-01-01T00:00:00Z -->\n\n${original}`;
    await writeFile(path, stampedSame, 'utf-8');

    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const entry = report.entries.find((e) => e.relativePath === 'CLAUDE.md');
    expect(entry?.status).toBe('match');
  });
});

describe('detectDrift — error handling', () => {
  it('throws DriftError when the target directory does not exist', async () => {
    await expect(
      detectDrift({ targetDir: '/tmp/embediq-nonexistent-xyz', answers: FIXTURE_ANSWERS }),
    ).rejects.toBeInstanceOf(DriftError);
  });

  it('throws DriftError when the answers file does not exist', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'embediq-drift-'));
    try {
      await expect(
        detectDrift({ targetDir: dir, answers: join(dir, 'nope.yaml') }),
      ).rejects.toBeInstanceOf(DriftError);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('throws DriftError when answers.yaml is malformed', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'embediq-drift-'));
    const answers = join(dir, 'bad.yaml');
    await writeFile(answers, 'STRAT_000: [unclosed\n', 'utf-8');
    try {
      await expect(detectDrift({ targetDir: dir, answers })).rejects.toBeInstanceOf(DriftError);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe('DriftReporter output', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'embediq-drift-'));
    await cp(FIXTURE_EXPECTED, dir, { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('produces parseable JSON', async () => {
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const text = renderDriftJson(report);
    expect(() => JSON.parse(text)).not.toThrow();
  });

  it('renders text with CLEAN status when there is no drift', async () => {
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const text = renderDriftText(report, { noColor: true });
    expect(text).toContain('CLEAN');
    expect(text).toContain('No drift detected');
  });

  it('renders text with DRIFT status and per-category grouping when drift is present', async () => {
    await writeFile(join(dir, '.claude/rules/extra.md'), '# extra\n', 'utf-8');
    const report = await detectDrift({ targetDir: dir, answers: FIXTURE_ANSWERS });
    const text = renderDriftText(report, { noColor: true });
    expect(text).toContain('DRIFT');
    expect(text).toContain('Extra files in managed subtree');
    expect(text).toContain('.claude/rules/extra.md');
  });
});
