import type { GeneratedFile } from '../types/index.js';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export type DiffStatus = 'new' | 'modified' | 'unchanged' | 'conflict';

export interface DiffResult {
  file: GeneratedFile;
  status: DiffStatus;
  existingContent?: string;
}

export interface DiffSummary {
  results: DiffResult[];
  newFiles: number;
  modifiedFiles: number;
  unchangedFiles: number;
  conflictFiles: number;
}

export function analyzeDiffs(
  files: GeneratedFile[],
  targetDir: string,
): DiffSummary {
  const results = files.map((file): DiffResult => {
    const fullPath = join(targetDir, file.relativePath);

    if (!existsSync(fullPath)) {
      return { file, status: 'new' };
    }

    const existing = readFileSync(fullPath, 'utf-8');

    if (existing === file.content) {
      return { file, status: 'unchanged' };
    }

    const isEmbediqGenerated = existing.includes('Generated by EmbedIQ');

    if (isEmbediqGenerated) {
      return { file, status: 'modified', existingContent: existing };
    } else {
      return { file, status: 'conflict', existingContent: existing };
    }
  });

  return {
    results,
    newFiles: results.filter(r => r.status === 'new').length,
    modifiedFiles: results.filter(r => r.status === 'modified').length,
    unchangedFiles: results.filter(r => r.status === 'unchanged').length,
    conflictFiles: results.filter(r => r.status === 'conflict').length,
  };
}
