import type { GeneratedFile } from '../types/index.js';

export const EMBEDIQ_SCHEMA_VERSION = 2;
export const EMBEDIQ_VERSION = '2.0.0';

export const EMBEDIQ_HOMEPAGE = 'https://github.com/asq-sheriff/embediq';

/**
 * Courtesy attribution appended to every generation stamp. EmbedIQ is
 * MIT-licensed, so this is a credit, not a license obligation — users are free
 * to keep or remove it. It deliberately rides on the same line as the machine
 * stamp: the evaluator (`normalizers.ts`) and the drift-detector strip any line
 * matching the `Generated by EmbedIQ v… | schema:… | <timestamp>` substring, so
 * the credit is removed alongside the timestamp during scoring and drift
 * comparison — it never perturbs golden scoring and never registers as drift,
 * yet it stays visible in the files users actually receive.
 */
export const EMBEDIQ_CREDIT = `${EMBEDIQ_HOMEPAGE} · a Praglogic project (MIT) · please keep this credit`;

export function stampGeneratedFile(file: GeneratedFile): GeneratedFile {
  const timestamp = new Date().toISOString();
  const ext = file.relativePath.split('.').pop()?.toLowerCase();
  const stamp = `Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp} · ${EMBEDIQ_CREDIT}`;

  let header: string;

  switch (ext) {
    case 'md':
      header = `<!-- ${stamp} -->\n\n`;
      break;

    case 'json': {
      try {
        const parsed = JSON.parse(file.content);
        parsed._embediq = {
          generator: 'EmbedIQ',
          homepage: EMBEDIQ_HOMEPAGE,
          project: 'Praglogic',
          license: 'MIT',
          credit: 'Generated by EmbedIQ — please keep this credit',
          version: EMBEDIQ_VERSION,
          schema: EMBEDIQ_SCHEMA_VERSION,
          generatedAt: timestamp,
        };
        return {
          ...file,
          content: JSON.stringify(parsed, null, 2),
        };
      } catch {
        header = `// ${stamp}\n`;
      }
      break;
    }

    case 'py':
      header = `# ${stamp}\n\n`;
      break;

    case 'yaml':
    case 'yml':
      header = `# ${stamp}\n\n`;
      break;

    default:
      header = `# ${stamp}\n\n`;
  }

  return {
    ...file,
    content: header + file.content,
  };
}
