import type { GeneratedFile } from '../types/index.js';

export const EMBEDIQ_SCHEMA_VERSION = 2;
export const EMBEDIQ_VERSION = '2.0.0';

export function stampGeneratedFile(file: GeneratedFile): GeneratedFile {
  const timestamp = new Date().toISOString();
  const ext = file.relativePath.split('.').pop()?.toLowerCase();

  let header: string;

  switch (ext) {
    case 'md':
      header = `<!-- Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp} -->\n\n`;
      break;

    case 'json': {
      try {
        const parsed = JSON.parse(file.content);
        parsed._embediq = {
          version: EMBEDIQ_VERSION,
          schema: EMBEDIQ_SCHEMA_VERSION,
          generatedAt: timestamp,
        };
        return {
          ...file,
          content: JSON.stringify(parsed, null, 2),
        };
      } catch {
        header = `// Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp}\n`;
      }
      break;
    }

    case 'py':
      header = `# Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp}\n\n`;
      break;

    case 'yaml':
    case 'yml':
      header = `# Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp}\n\n`;
      break;

    default:
      header = `# Generated by EmbedIQ v${EMBEDIQ_VERSION} | schema:${EMBEDIQ_SCHEMA_VERSION} | ${timestamp}\n\n`;
  }

  return {
    ...file,
    content: header + file.content,
  };
}
