import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { analyzeDiffs } from '../../src/synthesizer/diff-analyzer.js';
import type { GeneratedFile } from '../../src/types/index.js';
import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const TEST_DIR = join(process.cwd(), 'tests', '.tmp-diff-test');

beforeEach(() => {
  if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true });
  mkdirSync(TEST_DIR, { recursive: true });
});

afterEach(() => {
  if (existsSync(TEST_DIR)) rmSync(TEST_DIR, { recursive: true });
});

describe('analyzeDiffs', () => {
  it('marks files as "new" when target dir is empty', () => {
    const files: GeneratedFile[] = [
      { relativePath: 'CLAUDE.md', content: '# Test', description: '' },
      { relativePath: '.claude/settings.json', content: '{}', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.newFiles).toBe(2);
    expect(summary.modifiedFiles).toBe(0);
    expect(summary.unchangedFiles).toBe(0);
    expect(summary.conflictFiles).toBe(0);
  });

  it('marks files as "unchanged" when content matches exactly', () => {
    const content = '<!-- Generated by EmbedIQ v2.0.0 -->\n# Test';
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), content);

    const files: GeneratedFile[] = [
      { relativePath: 'CLAUDE.md', content, description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.unchangedFiles).toBe(1);
  });

  it('marks EmbedIQ-generated files as "modified" when content differs', () => {
    writeFileSync(
      join(TEST_DIR, 'CLAUDE.md'),
      '<!-- Generated by EmbedIQ v1.0.0 -->\n# Old content',
    );

    const files: GeneratedFile[] = [
      { relativePath: 'CLAUDE.md', content: '<!-- Generated by EmbedIQ v2.0.0 -->\n# New content', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.modifiedFiles).toBe(1);
  });

  it('marks user-created files as "conflict" when they lack EmbedIQ header', () => {
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), '# My hand-written CLAUDE.md');

    const files: GeneratedFile[] = [
      { relativePath: 'CLAUDE.md', content: '<!-- Generated by EmbedIQ -->\n# New', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.conflictFiles).toBe(1);
  });

  it('provides existing content for modified and conflict files', () => {
    const existing = '<!-- Generated by EmbedIQ v1.0.0 -->\n# Old';
    writeFileSync(join(TEST_DIR, 'CLAUDE.md'), existing);

    const files: GeneratedFile[] = [
      { relativePath: 'CLAUDE.md', content: '<!-- Generated by EmbedIQ v2.0.0 -->\n# New', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.results[0].existingContent).toBe(existing);
  });

  it('handles nested directories correctly', () => {
    mkdirSync(join(TEST_DIR, '.claude', 'rules'), { recursive: true });
    writeFileSync(
      join(TEST_DIR, '.claude', 'rules', 'testing.md'),
      '<!-- Generated by EmbedIQ -->\n# Testing',
    );

    const files: GeneratedFile[] = [
      { relativePath: '.claude/rules/testing.md', content: '<!-- Generated by EmbedIQ -->\n# Updated', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.modifiedFiles).toBe(1);
  });

  it('handles mixed statuses in a single analysis', () => {
    writeFileSync(join(TEST_DIR, 'existing.md'), '# User file');
    writeFileSync(join(TEST_DIR, 'generated.md'), '<!-- Generated by EmbedIQ -->\n# Old');

    const files: GeneratedFile[] = [
      { relativePath: 'new-file.md', content: '# New', description: '' },
      { relativePath: 'existing.md', content: '# Overwrite', description: '' },
      { relativePath: 'generated.md', content: '<!-- Generated by EmbedIQ -->\n# Updated', description: '' },
    ];
    const summary = analyzeDiffs(files, TEST_DIR);
    expect(summary.newFiles).toBe(1);
    expect(summary.conflictFiles).toBe(1);
    expect(summary.modifiedFiles).toBe(1);
  });
});
