import { describe, it, expect } from 'vitest';
import { stampGeneratedFile, EMBEDIQ_VERSION, EMBEDIQ_SCHEMA_VERSION } from '../../src/synthesizer/generation-header.js';
import type { GeneratedFile } from '../../src/types/index.js';

describe('stampGeneratedFile', () => {
  it('adds HTML comment header to .md files', () => {
    const file: GeneratedFile = {
      relativePath: 'CLAUDE.md',
      content: '# My Project',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.content).toContain('<!-- Generated by EmbedIQ');
    expect(stamped.content).toContain(`v${EMBEDIQ_VERSION}`);
    expect(stamped.content).toContain(`schema:${EMBEDIQ_SCHEMA_VERSION}`);
    expect(stamped.content).toContain('# My Project');
  });

  it('adds _embediq key to valid .json files', () => {
    const file: GeneratedFile = {
      relativePath: '.claude/settings.json',
      content: '{"hooks": {}}',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    const parsed = JSON.parse(stamped.content);
    expect(parsed._embediq).toBeDefined();
    expect(parsed._embediq.version).toBe(EMBEDIQ_VERSION);
    expect(parsed._embediq.schema).toBe(EMBEDIQ_SCHEMA_VERSION);
    expect(parsed._embediq.generatedAt).toBeTruthy();
    expect(parsed.hooks).toEqual({});
  });

  it('adds comment header for invalid JSON content', () => {
    const file: GeneratedFile = {
      relativePath: 'something.json',
      content: 'not valid json',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.content).toContain('// Generated by EmbedIQ');
  });

  it('adds Python comment header to .py files', () => {
    const file: GeneratedFile = {
      relativePath: '.claude/hooks/dlp-scanner.py',
      content: '#!/usr/bin/env python3\nimport sys',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.content).toContain('# Generated by EmbedIQ');
    expect(stamped.content).toContain('#!/usr/bin/env python3');
  });

  it('adds YAML comment header to .yaml files', () => {
    const file: GeneratedFile = {
      relativePath: 'association_map.yaml',
      content: 'key: value',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.content).toContain('# Generated by EmbedIQ');
    expect(stamped.content).toContain('key: value');
  });

  it('preserves file metadata (relativePath, description)', () => {
    const file: GeneratedFile = {
      relativePath: 'test.md',
      content: 'hello',
      description: 'test description',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.relativePath).toBe('test.md');
    expect(stamped.description).toBe('test description');
  });

  it('uses default comment header for unknown extensions', () => {
    const file: GeneratedFile = {
      relativePath: '.claudeignore',
      content: 'node_modules/',
      description: 'test',
    };
    const stamped = stampGeneratedFile(file);
    expect(stamped.content).toContain('Generated by EmbedIQ');
  });
});
