import { describe, it, expect, beforeEach, vi } from 'vitest';
import type { Counter, Histogram, Meter, MetricOptions, UpDownCounter } from '@opentelemetry/api';
import { InMemoryEventBus, OtelSubscriber } from '../../src/events/index.js';
import { Dimension } from '../../src/types/index.js';

function flushMicrotasks(): Promise<void> {
  return new Promise((resolve) => setImmediate(resolve));
}

interface CounterCall {
  value: number;
  attributes: Record<string, unknown> | undefined;
}

class SpyCounter implements Counter {
  calls: CounterCall[] = [];
  add(value: number, attributes?: Record<string, unknown>): void {
    this.calls.push({ value, attributes });
  }
}

class SpyMeter implements Meter {
  counters = new Map<string, SpyCounter>();

  createCounter(name: string, _options?: MetricOptions): Counter {
    const c = new SpyCounter();
    this.counters.set(name, c);
    return c;
  }

  // Satisfy the Meter interface — other methods are unused in the subscriber.
  createUpDownCounter(): UpDownCounter {
    throw new Error('not used');
  }
  createHistogram(): Histogram {
    throw new Error('not used');
  }
  createObservableCounter = (() => ({})) as unknown as Meter['createObservableCounter'];
  createObservableGauge = (() => ({})) as unknown as Meter['createObservableGauge'];
  createObservableUpDownCounter = (() =>
    ({})) as unknown as Meter['createObservableUpDownCounter'];
  addBatchObservableCallback = (() => undefined) as unknown as Meter['addBatchObservableCallback'];
  removeBatchObservableCallback = (() =>
    undefined) as unknown as Meter['removeBatchObservableCallback'];
  createGauge = (() => ({})) as unknown as Meter['createGauge'];
}

describe('OtelSubscriber', () => {
  let bus: InMemoryEventBus;
  let meter: SpyMeter;
  let subscriber: OtelSubscriber;

  beforeEach(() => {
    bus = new InMemoryEventBus();
    meter = new SpyMeter();
    subscriber = new OtelSubscriber(meter);
    subscriber.register(bus);
  });

  describe('counter construction', () => {
    it('creates the three orchestrator-compatible counters up front', () => {
      expect(meter.counters.has('embediq.files_generated')).toBe(true);
      expect(meter.counters.has('embediq.generation_runs')).toBe(true);
      expect(meter.counters.has('embediq.validations')).toBe(true);
    });
  });

  describe('file:generated', () => {
    it('increments embediq.files_generated by 1 per event', async () => {
      bus.emit('file:generated', { relativePath: 'a.md', size: 10 });
      bus.emit('file:generated', { relativePath: 'b.md', size: 20 });
      bus.emit('file:generated', { relativePath: 'c.md', size: 30 });
      await flushMicrotasks();

      const counter = meter.counters.get('embediq.files_generated')!;
      expect(counter.calls).toHaveLength(3);
      expect(counter.calls.every((c) => c.value === 1)).toBe(true);
    });
  });

  describe('generation:started', () => {
    it('increments embediq.generation_runs with the generator_count label', async () => {
      bus.emit('generation:started', { generatorCount: 12 });
      await flushMicrotasks();

      const counter = meter.counters.get('embediq.generation_runs')!;
      expect(counter.calls).toHaveLength(1);
      expect(counter.calls[0]).toEqual({
        value: 1,
        attributes: { generator_count: 12 },
      });
    });

    it('records generator_count for each run independently', async () => {
      bus.emit('generation:started', { generatorCount: 12 });
      bus.emit('generation:started', { generatorCount: 10 });
      await flushMicrotasks();

      const counter = meter.counters.get('embediq.generation_runs')!;
      expect(counter.calls.map((c) => c.attributes?.generator_count)).toEqual([12, 10]);
    });
  });

  describe('validation:completed', () => {
    it('labels passed="true" when failCount is zero', async () => {
      bus.emit('validation:completed', { passCount: 5, failCount: 0, checks: [] });
      await flushMicrotasks();

      const counter = meter.counters.get('embediq.validations')!;
      expect(counter.calls).toHaveLength(1);
      expect(counter.calls[0].attributes).toEqual({ passed: 'true' });
    });

    it('labels passed="false" when failCount is non-zero', async () => {
      bus.emit('validation:completed', { passCount: 3, failCount: 2, checks: [] });
      await flushMicrotasks();

      const counter = meter.counters.get('embediq.validations')!;
      expect(counter.calls[0].attributes).toEqual({ passed: 'false' });
    });
  });

  describe('events without counter mappings', () => {
    it('does not throw or increment counters for question/answer/dimension events', async () => {
      bus.emit('question:presented', {
        questionId: 'STRAT_001',
        dimension: Dimension.STRATEGIC_INTENT,
      });
      bus.emit('answer:received', { questionId: 'STRAT_001', answerValue: 'yes' });
      bus.emit('dimension:completed', {
        dimension: Dimension.STRATEGIC_INTENT,
        questionsAnswered: 1,
      });
      bus.emit('session:started', { sessionId: 's1' });
      bus.emit('session:completed', { sessionId: 's1', fileCount: 0 });
      await flushMicrotasks();

      expect(meter.counters.get('embediq.files_generated')!.calls).toHaveLength(0);
      expect(meter.counters.get('embediq.generation_runs')!.calls).toHaveLength(0);
      expect(meter.counters.get('embediq.validations')!.calls).toHaveLength(0);
    });
  });

  describe('span event forwarding', () => {
    it('adds a span event on the active span for every bus event', async () => {
      const addEvent = vi.fn();
      const { trace } = await import('@opentelemetry/api');
      const spy = vi.spyOn(trace, 'getActiveSpan').mockReturnValue({
        addEvent,
      } as unknown as ReturnType<typeof trace.getActiveSpan>);

      try {
        bus.emit('session:started', { sessionId: 's1' });
        bus.emit('file:generated', { relativePath: 'x', size: 1 });
        await flushMicrotasks();

        expect(addEvent).toHaveBeenCalledWith('session:started');
        expect(addEvent).toHaveBeenCalledWith('file:generated');
      } finally {
        spy.mockRestore();
      }
    });

    it('is a safe no-op when there is no active span', async () => {
      const { trace } = await import('@opentelemetry/api');
      const spy = vi.spyOn(trace, 'getActiveSpan').mockReturnValue(undefined);

      try {
        expect(() => bus.emit('session:started', { sessionId: 's1' })).not.toThrow();
        await flushMicrotasks();
      } finally {
        spy.mockRestore();
      }
    });
  });
});
