import type { ConfigGenerator } from '../generator.js';
import { TargetFormat } from '../target-format.js';
import type { SetupConfig, GeneratedFile, UserProfile } from '../../types/index.js';
import { MarkdownBuilder } from '../../util/markdown-builder.js';

/**
 * Cross-agent `AGENTS.md` generator. `AGENTS.md` is the emerging universal
 * format consumed by Codex, Cursor, Copilot agents, Aider, and others — a
 * shared "what to know about this repo" document that tool-specific files
 * (Cursor MDC, Copilot instructions, etc.) layer on top of.
 *
 * Section order follows the community convention: Project → Stack →
 * Commands → Boundaries → Rules → Terminology. Non-technical roles get
 * a coworker-shaped document that retains the same top-level anchors so
 * downstream tools can still find them.
 */
export class AgentsMdGenerator implements ConfigGenerator {
  name = 'AGENTS.md';
  target = TargetFormat.AGENTS_MD;

  generate(config: SetupConfig): GeneratedFile[] {
    const { profile } = config;
    const isNonTechnical = ['ba', 'pm', 'executive'].includes(profile.role);
    const content = isNonTechnical
      ? this.renderNonTechnical(profile)
      : this.renderTechnical(profile);

    return [
      {
        relativePath: 'AGENTS.md',
        content,
        description: 'Cross-agent instructions (AGENTS.md universal format)',
      },
    ];
  }

  private renderTechnical(profile: UserProfile): string {
    const md = new MarkdownBuilder();
    md.h1(profile.businessDomain || 'Project');
    md.paragraph(
      'This file is read by AI coding agents that understand the `AGENTS.md` format. It is generated by EmbedIQ from an adaptive Q&A and must be kept in sync with the rest of the repository configuration.',
    );

    // Stack
    md.h2('Stack');
    if (profile.languages.length > 0) md.bullet(`Languages: ${profile.languages.join(', ')}`);
    const frameworks = profile.techStack.filter((t) => !profile.languages.includes(t));
    if (frameworks.length > 0) md.bullet(`Frameworks: ${frameworks.join(', ')}`);
    if (profile.devOps.buildTools.length > 0) md.bullet(`Build: ${profile.devOps.buildTools.join(', ')}`);
    if (profile.devOps.testFrameworks.length > 0) md.bullet(`Testing: ${profile.devOps.testFrameworks.join(', ')}`);
    if (profile.devOps.cicd) md.bullet(`CI/CD: ${profile.devOps.cicd}`);
    if (profile.devOps.containerization.length > 0) md.bullet(`Containers: ${profile.devOps.containerization.join(', ')}`);
    md.blank();

    // Commands
    md.h2('Commands');
    const commandBullets = buildCommandBullets(profile);
    if (commandBullets.length === 0) {
      md.bullet('No project-specific commands detected — follow language-standard tooling.');
    } else {
      for (const b of commandBullets) md.bullet(b);
    }
    md.blank();

    // Boundaries (compliance + security)
    const boundaries = this.buildBoundaries(profile);
    if (boundaries.length > 0) {
      md.h2('Boundaries');
      md.paragraph(
        'Hard constraints that override general preferences — violating these blocks merges and may trigger compliance reviews.',
      );
      for (const b of boundaries) md.bullet(b);
      md.blank();
    }

    // Rules (conventions + quality)
    md.h2('Rules');
    md.bullet('Run tests before committing any change; do not skip failing tests.');
    md.bullet('Keep changes scoped to the task — avoid drive-by refactors unless requested.');
    md.bullet('Prefer editing existing files; do not create new files unless necessary.');
    const conventions = buildConventionBullets(profile);
    for (const b of conventions) md.bullet(b);
    if (profile.complianceFrameworks.length > 0) {
      md.bullet(
        `Consult tool-specific rule files (e.g. \`.claude/rules/*.md\`, \`.cursor/rules/*.mdc\`) for ${profile.complianceFrameworks
          .map((f) => f.toUpperCase())
          .join(', ')} details.`,
      );
    }
    md.blank();

    // Terminology
    md.h2('Terminology');
    const terminology = buildTerminologyBullets(profile);
    if (terminology.length === 0) {
      md.bullet(
        `${profile.businessDomain || 'Project'}: the product context this repository implements.`,
      );
    } else {
      for (const t of terminology) md.bullet(t);
    }
    md.blank();

    return md.build();
  }

  private renderNonTechnical(profile: UserProfile): string {
    const md = new MarkdownBuilder();
    const roleTitle = roleTitleFor(profile.role);
    md.h1(`${profile.businessDomain || 'Project'} — ${roleTitle} Workspace`);
    md.paragraph(
      `This repository uses AI coding agents as intelligent coworkers for ${roleTitle.toLowerCase()} tasks: research, analysis, documentation, and strategic thinking rather than code development.`,
    );

    md.h2('Stack');
    md.bullet(`Industry: ${formatIndustry(profile.industry)}`);
    if (profile.businessDomain) md.bullet(`Business domain: ${profile.businessDomain}`);

    md.h2('Commands');
    md.bullet('No build/test commands — this is a non-technical workspace.');

    if (profile.complianceFrameworks.length > 0) {
      md.h2('Boundaries');
      for (const fw of profile.complianceFrameworks) {
        md.bullet(`${fw.toUpperCase()} compliance applies to this domain — flag any violation in analysis or drafts.`);
      }
      md.bullet('Never include real PHI/PII/cardholder data in any generated artifact.');
      md.blank();
    }

    md.h2('Rules');
    md.bullet('Use clear, non-technical language in all outputs.');
    md.bullet('Cite sources and data when making claims.');
    md.bullet('Flag assumptions explicitly.');
    md.bullet('Provide an executive summary before detailed analysis.');
    md.bullet('Use tables and structured formats for comparisons.');
    md.blank();

    md.h2('Terminology');
    md.bullet(
      `${profile.businessDomain || 'Project'}: the strategic context behind every artifact in this repository.`,
    );
    md.blank();

    return md.build();
  }

  private buildBoundaries(profile: UserProfile): string[] {
    const out: string[] = [];
    if (profile.complianceFrameworks.includes('hipaa')) {
      out.push('HIPAA: never include PHI (names, MRNs, DOBs, dates of service) in code, comments, logs, or test data.');
    }
    if (profile.complianceFrameworks.includes('pci')) {
      out.push('PCI-DSS: never store CVV/CVC; mask card numbers to the last 4 digits in logs.');
    }
    if (profile.complianceFrameworks.includes('sox')) {
      out.push('SOX: financial reporting code requires documented approval and segregation of duties.');
    }
    if (profile.complianceFrameworks.includes('ferpa')) {
      out.push('FERPA: never expose student education records beyond authorized parties.');
    }
    if (profile.securityConcerns.includes('sensitive_data')) {
      out.push('Never hardcode secrets, API keys, passwords, or session tokens.');
    }
    if (profile.securityConcerns.includes('dlp')) {
      out.push('DLP scanners run on every tool invocation — matches block the write.');
    }
    if (profile.securityConcerns.includes('strict_permissions')) {
      out.push('Destructive operations (`rm -rf`, `git push --force`, `git reset --hard`) require explicit approval.');
    }
    if (profile.securityConcerns.includes('protected_files')) {
      out.push('Edits to protected files (lock files, production configs) require explicit approval.');
    }
    if (profile.securityConcerns.includes('output_review')) {
      out.push('Output review hooks scan generated code before file writes — expect deferred or blocked writes on matches.');
    }
    return out;
  }
}

// ─── Shared helpers (also used by Gemini and Windsurf generators) ─────────

export function buildCommandBullets(profile: UserProfile): string[] {
  const out: string[] = [];
  const buildTools = profile.devOps.buildTools;
  const testFrameworks = profile.devOps.testFrameworks;

  if (buildTools.includes('npm')) {
    out.push('Install: `npm install`');
    out.push('Build: `npm run build`');
  } else if (buildTools.includes('pip')) {
    out.push('Install: `pip install -r requirements.txt`');
  } else if (buildTools.includes('maven')) {
    out.push('Build: `mvn clean compile`');
  } else if (buildTools.includes('gradle')) {
    out.push('Build: `./gradlew build`');
  } else if (buildTools.includes('cargo')) {
    out.push('Build: `cargo build`');
  } else if (buildTools.includes('go_mod')) {
    out.push('Build: `go build ./...`');
  }

  if (testFrameworks.includes('jest')) {
    out.push('Test: `npm test`');
  } else if (testFrameworks.includes('pytest')) {
    out.push('Test: `pytest`');
  } else if (testFrameworks.includes('junit')) {
    if (buildTools.includes('maven')) out.push('Test: `mvn test`');
    else if (buildTools.includes('gradle')) out.push('Test: `./gradlew test`');
  } else if (testFrameworks.includes('go_test')) {
    out.push('Test: `go test ./...`');
  } else if (testFrameworks.includes('rspec')) {
    out.push('Test: `bundle exec rspec`');
  }

  if (testFrameworks.includes('playwright')) {
    out.push('E2E: `npx playwright test`');
  }

  return out;
}

export function buildConventionBullets(profile: UserProfile): string[] {
  const out: string[] = [];
  if (profile.languages.includes('typescript')) {
    out.push('TypeScript: strict mode; explicit return types on exports; `const` by default.');
  }
  if (profile.languages.includes('python')) {
    out.push('Python: PEP 8; type hints on all signatures; f-strings for formatting.');
  }
  if (profile.languages.includes('go')) {
    out.push('Go: handle every error; small interfaces; table-driven tests.');
  }
  if (profile.languages.includes('java')) {
    out.push('Java: records for value types; `Optional` instead of null returns; sealed hierarchies.');
  }
  if (profile.languages.includes('rust')) {
    out.push('Rust: clippy-clean; prefer `Result` over `unwrap()`; doc comments on public APIs.');
  }
  return out;
}

export function buildTerminologyBullets(profile: UserProfile): string[] {
  const out: string[] = [];
  if (profile.complianceFrameworks.includes('hipaa')) {
    out.push('PHI: Protected Health Information — any identifier linked to health data.');
    out.push('BAA: Business Associate Agreement — required contract with HIPAA-covered entities.');
  }
  if (profile.complianceFrameworks.includes('pci')) {
    out.push('CHD: Cardholder Data — PAN, expiration, service code, cardholder name.');
    out.push('SAD: Sensitive Authentication Data — CVV/CVC, PIN blocks, magnetic stripe data.');
  }
  if (profile.complianceFrameworks.includes('ferpa')) {
    out.push('PII: Personally Identifiable Information applied to student education records.');
  }
  if (profile.businessDomain) {
    out.push(`${profile.businessDomain}: the business domain this repository implements.`);
  }
  return out;
}

function roleTitleFor(role: string): string {
  const map: Record<string, string> = {
    ba: 'Business Analyst',
    pm: 'Product Manager',
    executive: 'Executive',
  };
  return map[role] ?? role;
}

function formatIndustry(industry: string): string {
  const map: Record<string, string> = {
    healthcare: 'Healthcare / Life Sciences',
    finance: 'Financial Services / Fintech',
    ecommerce: 'E-Commerce / Retail',
    saas: 'SaaS / Enterprise Software',
    education: 'Education / EdTech',
    government: 'Government / Public Sector',
    manufacturing: 'Manufacturing / IoT',
    media: 'Media / Entertainment / Gaming',
  };
  return map[industry] ?? industry;
}
