import type { ConfigGenerator } from '../generator.js';
import { TargetFormat } from '../target-format.js';
import type { SetupConfig, GeneratedFile, UserProfile } from '../../types/index.js';

/**
 * Aider generator — emits `.aider.conf.yml` plus `.aiderignore`. Wires
 * Aider's CLI pair-programmer to use the user's default Ollama model and
 * auto-test command. Adds `.aiderignore` to keep build artifacts and
 * sensitive files out of Aider's context window.
 *
 * Only runs when the user has opted into local AI (TECH_013) and selected
 * `aider` in TECH_017.
 */
export class AiderGenerator implements ConfigGenerator {
  name = 'aider';
  target = TargetFormat.AIDER;

  generate(config: SetupConfig): GeneratedFile[] {
    const { profile } = config;
    const defaultModel = profile.defaultLocalModel
      ?? profile.ollamaModels?.[0]
      ?? 'llama3.1:8b';
    const testCmd = inferTestCommand(profile);
    const lintCmd = inferLintCommand(profile);

    const conf = [
      `# Aider config — generated by EmbedIQ`,
      `# Default model points at a locally-running Ollama instance.`,
      `model: ollama/${defaultModel}`,
      profile.complianceFrameworks.length > 0
        ? `# Compliance frameworks active: ${profile.complianceFrameworks.join(', ')}`
        : null,
      ``,
      `# Lint + test on every change so the generated code stays green.`,
      `auto-lint: true`,
      lintCmd ? `lint-cmd: ${lintCmd}` : `# lint-cmd: <set per your stack>`,
      `auto-test: true`,
      testCmd ? `test-cmd: ${testCmd}` : `# test-cmd: <set per your stack>`,
      ``,
      `# Conservative defaults — no auto-commit, dry-run on dangerous ops.`,
      `auto-commits: false`,
      `dirty-commits: false`,
      `attribute-author: false`,
      `attribute-committer: false`,
    ]
      .filter((l) => l !== null)
      .join('\n') + '\n';

    const ignore = [
      `# Aider context-exclude — generated by EmbedIQ`,
      `# These patterns mirror .gitignore plus secrets / build artifacts.`,
      `node_modules/`,
      `dist/`,
      `out/`,
      `build/`,
      `coverage/`,
      `.env`,
      `.env.*`,
      `*.pem`,
      `*.key`,
      `*.log`,
    ];
    if (profile.complianceFrameworks.includes('hipaa')) {
      ignore.push(``, `# HIPAA — never load PHI into Aider's context`);
      ignore.push(`*.phi.json`, `*.phi.yaml`, `phi/`, `data/patients/`);
    }
    if (profile.complianceFrameworks.includes('pci')) {
      ignore.push(``, `# PCI-DSS — keep card data out of context`);
      ignore.push(`*cardholder*`, `data/cards/`);
    }
    ignore.push('');

    return [
      {
        relativePath: '.aider.conf.yml',
        content: conf,
        description: 'Aider configuration (.aider.conf.yml)',
      },
      {
        relativePath: '.aiderignore',
        content: ignore.join('\n'),
        description: 'Aider context exclusions (.aiderignore)',
      },
    ];
  }
}

/** Exposed for tests. */
export function shouldEmitAider(profile: UserProfile): boolean {
  return (
    profile.localAiEnabled === true &&
    Array.isArray(profile.ideIntegrations) &&
    profile.ideIntegrations.includes('aider')
  );
}

function inferTestCommand(profile: UserProfile): string | null {
  const langs = profile.languages;
  const tools = profile.devOps.buildTools;
  if (tools.includes('npm') || langs.includes('typescript') || langs.includes('javascript')) {
    return 'npm test';
  }
  if (langs.includes('python')) return 'pytest';
  if (langs.includes('go')) return 'go test ./...';
  if (langs.includes('rust')) return 'cargo test';
  if (langs.includes('java')) return 'mvn test';
  return null;
}

function inferLintCommand(profile: UserProfile): string | null {
  const langs = profile.languages;
  const tools = profile.devOps.buildTools;
  if (tools.includes('npm') || langs.includes('typescript') || langs.includes('javascript')) {
    return 'npm run lint';
  }
  if (langs.includes('python')) return 'ruff check .';
  if (langs.includes('go')) return 'go vet ./...';
  if (langs.includes('rust')) return 'cargo clippy';
  return null;
}
