import type { ConfigGenerator } from '../generator.js';
import { TargetFormat } from '../target-format.js';
import type { SetupConfig, GeneratedFile, UserProfile } from '../../types/index.js';

/**
 * Cursor rules generator — emits `.cursor/rules/*.mdc` files with MDC
 * YAML frontmatter. Cursor interprets three frontmatter fields:
 *   - `description`: one-liner shown in the rules UI
 *   - `alwaysApply`: true → injected into every request
 *   - `globs`: path patterns that scope the rule to matching edits
 *
 * Compliance and security rules are `alwaysApply: true` because a
 * regulated codebase must treat them as unconditional. Language rules
 * are glob-scoped so they only surface when editing that language's
 * files, keeping the context window lean.
 */
export class CursorRulesGenerator implements ConfigGenerator {
  name = 'cursor-rules';
  target = TargetFormat.CURSOR;

  generate(config: SetupConfig): GeneratedFile[] {
    const { profile } = config;
    const isNonTechnical = ['ba', 'pm', 'executive'].includes(profile.role);
    if (isNonTechnical) return [this.nonTechnicalProjectRule(profile)];

    const files: GeneratedFile[] = [];
    files.push(this.projectRule(profile));

    // Security / compliance rules — always-apply.
    if (profile.securityConcerns.length > 0 || profile.complianceFrameworks.length > 0) {
      files.push(this.securityRule(profile));
    }

    if (profile.complianceFrameworks.includes('hipaa')) {
      files.push(this.hipaaRule());
    }
    if (profile.complianceFrameworks.includes('pci')) {
      files.push(this.pciRule());
    }
    if (profile.complianceFrameworks.includes('ferpa')) {
      files.push(this.ferpaRule());
    }

    // Language-specific glob-scoped rules.
    for (const lang of profile.languages) {
      const rule = this.languageRule(lang);
      if (rule) files.push(rule);
    }

    // Testing standards apply to test paths only.
    files.push(this.testingRule());

    // Domain pack rule templates, path-scoped.
    if (config.domainPack?.ruleTemplates) {
      for (const tpl of config.domainPack.ruleTemplates) {
        if (tpl.requiresFramework && !profile.complianceFrameworks.includes(tpl.requiresFramework)) {
          continue;
        }
        const relativePath = `.cursor/rules/${basenameWithoutExt(tpl.filename)}.mdc`;
        if (files.some((f) => f.relativePath === relativePath)) continue;
        files.push({
          relativePath,
          content: renderMdc(
            {
              description: `${tpl.filename} — from domain pack`,
              alwaysApply: tpl.pathScope.length === 0,
              globs: tpl.pathScope.length > 0 ? tpl.pathScope : undefined,
            },
            stripExistingFrontmatter(tpl.content),
          ),
          description: `Cursor rule derived from domain-pack template ${tpl.filename}`,
        });
      }
    }

    return files;
  }

  private projectRule(profile: UserProfile): GeneratedFile {
    const lines: string[] = [];
    lines.push(`# ${profile.businessDomain || 'Project'} — Cursor Rules`);
    lines.push('');
    lines.push('Project-wide Cursor rules generated by EmbedIQ. Path-scoped rules in this same directory add language- and compliance-specific guidance automatically.');
    lines.push('');
    lines.push('## Stack');
    if (profile.languages.length > 0) lines.push(`- Languages: ${profile.languages.join(', ')}`);
    const frameworks = profile.techStack.filter((t) => !profile.languages.includes(t));
    if (frameworks.length > 0) lines.push(`- Frameworks: ${frameworks.join(', ')}`);
    if (profile.devOps.buildTools.length > 0) lines.push(`- Build: ${profile.devOps.buildTools.join(', ')}`);
    if (profile.devOps.testFrameworks.length > 0) lines.push(`- Testing: ${profile.devOps.testFrameworks.join(', ')}`);
    lines.push('');
    lines.push('## Ground rules');
    lines.push('- Run tests before committing; never commit code that fails tests.');
    lines.push('- Keep changes scoped to the task; avoid drive-by refactors.');
    lines.push('- Prefer editing existing files over creating new ones.');
    lines.push('- Never hardcode secrets, API keys, or credentials.');
    return {
      relativePath: '.cursor/rules/project.mdc',
      content: renderMdc(
        {
          description: 'Project-wide conventions and ground rules',
          alwaysApply: true,
        },
        lines.join('\n'),
      ),
      description: 'Always-applied project rule (.cursor/rules/project.mdc)',
    };
  }

  private securityRule(profile: UserProfile): GeneratedFile {
    const lines: string[] = [];
    lines.push('# Security Rules');
    lines.push('');
    lines.push('- Never hardcode secrets, API keys, passwords, or tokens.');
    lines.push('- Never log sensitive data (PII, PHI, credentials).');
    lines.push('- Validate all user input at system boundaries.');
    lines.push('- Use parameterized queries for all database access.');
    lines.push('- Follow OWASP Top 10 guidelines.');
    if (profile.securityConcerns.includes('phi')) {
      lines.push('- CRITICAL: no PHI in code, comments, test data, or logs.');
    }
    if (profile.securityConcerns.includes('pii')) {
      lines.push('- CRITICAL: no PII in code, comments, test data, or logs.');
    }
    if (profile.securityConcerns.includes('dlp')) {
      lines.push('- DLP scanners block writes that match sensitive-data patterns.');
    }
    if (profile.securityConcerns.includes('strict_permissions')) {
      lines.push('- Destructive shell operations require explicit approval.');
    }
    return {
      relativePath: '.cursor/rules/security.mdc',
      content: renderMdc(
        { description: 'Security rules (always applied)', alwaysApply: true },
        lines.join('\n'),
      ),
      description: 'Always-applied security rule (.cursor/rules/security.mdc)',
    };
  }

  private hipaaRule(): GeneratedFile {
    return {
      relativePath: '.cursor/rules/hipaa-compliance.mdc',
      content: renderMdc(
        {
          description: 'HIPAA compliance rules for healthcare data handling',
          alwaysApply: true,
        },
        [
          '# HIPAA Compliance',
          '',
          '- All PHI must be encrypted at rest and in transit.',
          '- Access to PHI must be logged and auditable.',
          '- Never include real patient data in test fixtures — use synthetic data only.',
          '- Implement minimum necessary access principle.',
          '- All PHI-handling code must have security review before merge.',
          '- Session audit trail is mandatory for all PHI access.',
        ].join('\n'),
      ),
      description: 'HIPAA compliance rule (always applied)',
    };
  }

  private pciRule(): GeneratedFile {
    return {
      relativePath: '.cursor/rules/pci-compliance.mdc',
      content: renderMdc(
        {
          description: 'PCI-DSS compliance rules for payment data',
          alwaysApply: true,
        },
        [
          '# PCI-DSS Compliance',
          '',
          '- Never store CVV/CVC data.',
          '- Card numbers must be masked in logs (last 4 digits only).',
          '- All payment processing must use approved tokenization.',
          '- Encrypt cardholder data in transit and at rest.',
        ].join('\n'),
      ),
      description: 'PCI-DSS compliance rule (always applied)',
    };
  }

  private ferpaRule(): GeneratedFile {
    return {
      relativePath: '.cursor/rules/ferpa-compliance.mdc',
      content: renderMdc(
        {
          description: 'FERPA compliance rules for student education records',
          alwaysApply: true,
        },
        [
          '# FERPA Compliance',
          '',
          '- Never expose student education records beyond authorized parties.',
          '- Log all access to student records.',
          '- Use synthetic data in fixtures — never real student identifiers.',
          '- Parental consent is required for disclosure of records for students under 18.',
        ].join('\n'),
      ),
      description: 'FERPA compliance rule (always applied)',
    };
  }

  private testingRule(): GeneratedFile {
    return {
      relativePath: '.cursor/rules/testing.mdc',
      content: renderMdc(
        {
          description: 'Testing standards for test files',
          globs: ['**/*.test.*', '**/*.spec.*', 'tests/**', '__tests__/**'],
        },
        [
          '# Testing Standards',
          '',
          '- Every new feature must have corresponding tests.',
          '- Use descriptive test names that explain the expected behavior.',
          '- Never commit code that fails existing tests.',
          '- Co-locate tests with source when the framework allows.',
        ].join('\n'),
      ),
      description: 'Testing rule (glob-scoped to test files)',
    };
  }

  private languageRule(language: string): GeneratedFile | null {
    switch (language) {
      case 'typescript':
        return {
          relativePath: '.cursor/rules/typescript.mdc',
          content: renderMdc(
            {
              description: 'TypeScript conventions',
              globs: ['**/*.ts', '**/*.tsx'],
            },
            [
              '# TypeScript Conventions',
              '',
              '- Strict mode is mandatory.',
              '- Explicit return types on exported functions.',
              '- Prefer `interface` over `type` for object shapes.',
              '- `const` by default; `let` only when reassignment is needed.',
              '- No `any` — use `unknown` and narrow with type guards.',
            ].join('\n'),
          ),
          description: 'TypeScript rule (.ts/.tsx scoped)',
        };
      case 'python':
        return {
          relativePath: '.cursor/rules/python.mdc',
          content: renderMdc(
            { description: 'Python conventions', globs: ['**/*.py'] },
            [
              '# Python Conventions',
              '',
              '- Follow PEP 8.',
              '- Type hints on all function signatures.',
              '- Use `pathlib` for file paths rather than `os.path`.',
              '- Use f-strings for string formatting.',
            ].join('\n'),
          ),
          description: 'Python rule (.py scoped)',
        };
      case 'go':
        return {
          relativePath: '.cursor/rules/go.mdc',
          content: renderMdc(
            { description: 'Go conventions', globs: ['**/*.go'] },
            [
              '# Go Conventions',
              '',
              '- Handle all errors; never use `_` for error returns.',
              '- Use table-driven tests.',
              '- Keep interfaces small (1-3 methods).',
            ].join('\n'),
          ),
          description: 'Go rule (.go scoped)',
        };
      case 'java':
        return {
          relativePath: '.cursor/rules/java.mdc',
          content: renderMdc(
            { description: 'Java/Kotlin conventions', globs: ['**/*.java', '**/*.kt'] },
            [
              '# Java Conventions',
              '',
              '- Use records for value types.',
              '- Prefer sealed interfaces for type hierarchies.',
              '- Use `Optional` instead of null returns.',
            ].join('\n'),
          ),
          description: 'Java/Kotlin rule (.java/.kt scoped)',
        };
      case 'rust':
        return {
          relativePath: '.cursor/rules/rust.mdc',
          content: renderMdc(
            { description: 'Rust conventions', globs: ['**/*.rs'] },
            [
              '# Rust Conventions',
              '',
              '- Use clippy with `#![deny(clippy::all)]`.',
              '- Prefer `Result` over `unwrap()`.',
              '- Document public APIs with `///` doc comments.',
            ].join('\n'),
          ),
          description: 'Rust rule (.rs scoped)',
        };
      default:
        return null;
    }
  }

  private nonTechnicalProjectRule(profile: UserProfile): GeneratedFile {
    const roleTitle = profile.role === 'ba' ? 'Business Analyst'
      : profile.role === 'pm' ? 'Product Manager'
      : 'Executive';
    const lines = [
      `# ${profile.businessDomain || 'Project'} — ${roleTitle} Workspace`,
      '',
      `Cursor is used here as an intelligent coworker for ${roleTitle.toLowerCase()} tasks — research, analysis, documentation, not code development.`,
      '',
      '- Use clear, non-technical language.',
      '- Cite sources and data when making claims.',
      '- Flag assumptions explicitly.',
      '- Provide an executive summary before detailed analysis.',
    ];
    return {
      relativePath: '.cursor/rules/project.mdc',
      content: renderMdc(
        {
          description: `${roleTitle} workspace conventions`,
          alwaysApply: true,
        },
        lines.join('\n'),
      ),
      description: 'Non-technical workspace rule (always applied)',
    };
  }
}

// ─── MDC rendering ────────────────────────────────────────────────────────

interface MdcFrontmatter {
  description?: string;
  alwaysApply?: boolean;
  globs?: readonly string[];
}

function renderMdc(frontmatter: MdcFrontmatter, body: string): string {
  const lines: string[] = ['---'];
  if (frontmatter.description) lines.push(`description: ${yamlString(frontmatter.description)}`);
  if (frontmatter.alwaysApply !== undefined) {
    lines.push(`alwaysApply: ${frontmatter.alwaysApply ? 'true' : 'false'}`);
  }
  if (frontmatter.globs && frontmatter.globs.length > 0) {
    lines.push('globs:');
    for (const g of frontmatter.globs) lines.push(`  - ${yamlString(g)}`);
  }
  lines.push('---');
  lines.push('');
  lines.push(body.replace(/\s+$/u, ''));
  lines.push('');
  return lines.join('\n');
}

/** Quote values containing special YAML characters; leave simple tokens unquoted. */
function yamlString(s: string): string {
  if (/^[A-Za-z0-9_\-./*: ]+$/u.test(s) && !s.includes(': ')) {
    return `"${s.replace(/"/g, '\\"')}"`;
  }
  return `"${s.replace(/"/g, '\\"')}"`;
}

function basenameWithoutExt(filename: string): string {
  return filename.replace(/\.(md|mdc|txt)$/i, '');
}

/** Strip an existing `---` YAML frontmatter block so we can attach our own. */
function stripExistingFrontmatter(content: string): string {
  if (!content.startsWith('---')) return content;
  const end = content.indexOf('\n---', 3);
  if (end < 0) return content;
  return content.slice(end + 4).replace(/^\s+/, '');
}
