import type { ConfigGenerator } from '../generator.js';
import { TargetFormat } from '../target-format.js';
import type { GenerationContext, GeneratedFile, UserProfile } from '../../types/index.js';
import { MarkdownBuilder } from '../../util/markdown-builder.js';
import {
  buildCommandBullets,
  buildConventionBullets,
  buildTerminologyBullets,
} from './agents-md.js';

/**
 * JetBrains IDE generator (IntelliJ, PyCharm, WebStorm, Rider, etc.).
 * Emits when the team uses JetBrains tools (TECH_004 / `profile.devOps.ide`
 * includes `jetbrains`):
 *
 *  - `.junie/guidelines.md` — project guidelines for JetBrains' Junie agent,
 *    also surfaced to AI Assistant. The JetBrains-native equivalent of
 *    CLAUDE.md / AGENTS.md. Built from the same profile-derived helpers the
 *    AGENTS.md generator uses, so guidance stays consistent across agents.
 *  - `.aiignore` — JetBrains AI honors this to exclude paths from AI context;
 *    high-value for regulated repos (keeps PHI/PII fixtures out of context).
 *
 * GitHub Copilot for JetBrains reads `.github/copilot-instructions.md`, which
 * the Copilot generator already produces when the `copilot` target is
 * selected — so no extra file is needed for that path (SETUP.md explains it).
 *
 * Carries `TargetFormat.CLAUDE` (project infrastructure, not agent-specific).
 * No-op for non-technical roles and when JetBrains isn't selected.
 */
export class JetBrainsGenerator implements ConfigGenerator {
  name = 'jetbrains';
  target = TargetFormat.CLAUDE;

  generate(config: GenerationContext): GeneratedFile[] {
    const { profile } = config;
    if (['ba', 'pm', 'executive'].includes(profile.role)) return [];
    if (!(profile.devOps.ide ?? []).includes('jetbrains')) return [];

    return [
      {
        relativePath: '.junie/guidelines.md',
        content: renderJunieGuidelines(profile),
        description: 'JetBrains Junie / AI Assistant project guidelines',
      },
      {
        relativePath: '.aiignore',
        content: renderAiIgnore(profile),
        description: 'JetBrains AI context exclusions',
      },
    ];
  }
}

function renderJunieGuidelines(profile: UserProfile): string {
  const md = new MarkdownBuilder();
  md.h1(`${profile.businessDomain || 'Project'} — JetBrains Guidelines`);
  md.paragraph(
    'Project guidelines for JetBrains Junie and AI Assistant. Generated by EmbedIQ from an adaptive Q&A — keep in sync with the rest of the repository configuration.',
  );

  md.h2('Stack');
  if (profile.languages.length > 0) md.bullet(`Languages: ${profile.languages.join(', ')}`);
  const frameworks = profile.techStack.filter((t) => !profile.languages.includes(t));
  if (frameworks.length > 0) md.bullet(`Frameworks: ${frameworks.join(', ')}`);
  if (profile.devOps.buildTools.length > 0) md.bullet(`Build: ${profile.devOps.buildTools.join(', ')}`);
  if (profile.devOps.testFrameworks.length > 0) md.bullet(`Testing: ${profile.devOps.testFrameworks.join(', ')}`);
  if (profile.devOps.cicd) md.bullet(`CI/CD: ${profile.devOps.cicd}`);
  if (profile.devOps.cloudTarget) md.bullet(`Cloud: ${profile.devOps.cloudTarget}`);
  md.blank();

  md.h2('Commands');
  const commandBullets = buildCommandBullets(profile);
  if (commandBullets.length === 0) {
    md.bullet('No project-specific commands detected — follow language-standard tooling.');
  } else {
    for (const b of commandBullets) md.bullet(b);
  }
  md.blank();

  const boundaries = buildBoundaries(profile);
  if (boundaries.length > 0) {
    md.h2('Boundaries');
    md.paragraph('Hard constraints that override general preferences.');
    for (const b of boundaries) md.bullet(b);
    md.blank();
  }

  md.h2('Rules');
  md.bullet('Run tests before committing any change; do not skip failing tests.');
  md.bullet('Keep changes scoped to the task — avoid drive-by refactors unless requested.');
  md.bullet('Prefer editing existing files; do not create new files unless necessary.');
  for (const b of buildConventionBullets(profile)) md.bullet(b);
  md.blank();

  const terminology = buildTerminologyBullets(profile);
  if (terminology.length > 0) {
    md.h2('Terminology');
    for (const t of terminology) md.bullet(t);
    md.blank();
  }

  return md.build();
}

/** Boundaries mirror the AGENTS.md generator's compliance/security set so
 *  the JetBrains guidance carries the same hard constraints. */
function buildBoundaries(profile: UserProfile): string[] {
  const out: string[] = [];
  if (profile.complianceFrameworks.includes('hipaa')) {
    out.push('HIPAA: never include PHI (names, MRNs, DOBs, dates of service) in code, comments, logs, or test data.');
  }
  if (profile.complianceFrameworks.includes('pci')) {
    out.push('PCI-DSS: never store CVV/CVC; mask card numbers to the last 4 digits in logs.');
  }
  if (profile.complianceFrameworks.includes('ferpa')) {
    out.push('FERPA: never expose student education records beyond authorized parties.');
  }
  if (profile.securityConcerns.includes('sensitive_data')) {
    out.push('Never hardcode secrets, API keys, passwords, or session tokens.');
  }
  return out;
}

function renderAiIgnore(profile: UserProfile): string {
  const lines: string[] = [
    '# JetBrains AI context exclusions',
    '# Files matched here are excluded from AI Assistant / Junie context.',
    '',
    '# Dependencies and build outputs',
    'node_modules/',
    '.venv/',
    'dist/',
    'build/',
    'target/',
    'bin/',
    'obj/',
    '',
    '# Environment and secrets',
    '.env',
    '.env.*',
    '*.pem',
    '*.key',
    '*.p12',
    '',
  ];

  if (profile.securityConcerns.includes('phi')) {
    lines.push('# PHI data (HIPAA)', 'patient_data/', 'phi/', 'health_records/', '**/phi/**', '');
  }
  if (profile.securityConcerns.includes('pii')) {
    lines.push('# PII data', 'pii/', 'personal_data/', '');
  }

  const restrictedPaths = profile.answers.get('REG_006')?.value;
  if (typeof restrictedPaths === 'string' && restrictedPaths.trim()) {
    lines.push('# Custom restricted paths');
    for (const path of restrictedPaths.split(/[,\n]/).map((p) => p.trim()).filter(Boolean)) {
      lines.push(path);
    }
    lines.push('');
  }

  return lines.join('\n');
}
